CREATE TABLE "mobile_money_transaction" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mobile_money_transaction_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"transaction_id" bigint NOT NULL,
	"provider_code" varchar(20),
	"customer_msisdn" varchar(20),
	"merchant_msisdn" varchar(20),
	"external_reference_id" varchar(100) UNIQUE,
	"request_sent_at" timestamp with time zone,
	"callback_received_at" timestamp with time zone,
	"callback_status" varchar(20),
	"callback_payload" jsonb,
	"retry_count" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notification" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"notification_type" varchar(50),
	"title" varchar(255),
	"message" text,
	"related_entity_type" varchar(50),
	"related_entity_id" bigint,
	"action_url" varchar(500),
	"is_read" boolean DEFAULT false,
	"read_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "payment_method" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payment_method_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"payment_type" varchar(30) NOT NULL,
	"is_primary" boolean DEFAULT false,
	"mobile_money_provider" varchar(50),
	"mobile_money_number" varchar(20),
	"mobile_money_account_name" varchar(100),
	"bank_account_number" varchar(50),
	"bank_name" varchar(100),
	"account_holder_name" varchar(100),
	"swift_code" varchar(20),
	"card_last_four" varchar(4),
	"card_brand" varchar(20),
	"card_expiry_month" smallint,
	"card_expiry_year" smallint,
	"is_verified" boolean DEFAULT false,
	"verification_token" varchar(255),
	"verification_token_expires_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "payment_type_check" CHECK (payment_type IN ('mobile_money','cash','bank_transfer','card'))
);
--> statement-breakpoint
CREATE TABLE "provider" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "provider_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"company_name" varchar(255) NOT NULL,
	"owner_phone" varchar(20) NOT NULL,
	"owner_email" varchar(255),
	"registration_number" varchar(50) UNIQUE,
	"tax_id" varchar(50),
	"country_code" varchar(5) DEFAULT 'TG',
	"is_active" boolean DEFAULT true,
	"is_verified" boolean DEFAULT false,
	"verification_date" timestamp,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"bank_account_name" varchar(255),
	"bank_account_number" varchar(50),
	"bank_name" varchar(100),
	"swift_code" varchar(20),
	"mobile_money_number" varchar(20),
	"mobile_money_provider" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "provider_availability" (
	"id" bigint PRIMARY KEY,
	"provider_id" bigint NOT NULL,
	"day_of_week" smallint,
	"start_time" time NOT NULL,
	"end_time" time NOT NULL,
	"is_available" boolean DEFAULT true,
	"break_start" time,
	"break_end" time,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "day_of_week_check" CHECK (day_of_week BETWEEN 0 AND 6)
);
--> statement-breakpoint
CREATE TABLE "provider_metric" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "provider_metric_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"provider_id" bigint NOT NULL UNIQUE,
	"total_completed_services" integer DEFAULT 0,
	"average_rating" numeric(3,2) DEFAULT '0',
	"total_ratings_count" integer DEFAULT 0,
	"response_time_average_hours" numeric(8,2) DEFAULT '0',
	"completion_rate_percentage" numeric(5,2) DEFAULT '100',
	"cancellation_rate_percentage" numeric(5,2) DEFAULT '0',
	"customer_satisfaction_percentage" numeric(5,2) DEFAULT '100',
	"on_time_completion_percentage" numeric(5,2) DEFAULT '100',
	"last_30_days_services" integer DEFAULT 0,
	"last_30_days_rating_average" numeric(3,2) DEFAULT '0',
	"risk_score" numeric(3,2) DEFAULT '0',
	"trustworthiness_score" numeric(3,2) DEFAULT '100',
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rating" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rating_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"service_request_id" bigint NOT NULL,
	"provider_id" bigint NOT NULL,
	"rater_id" bigint NOT NULL,
	"rating_score" numeric(2,1) NOT NULL,
	"quality_score" numeric(2,1),
	"timeliness_score" numeric(2,1),
	"communication_score" numeric(2,1),
	"review_title" varchar(200),
	"review_text" text,
	"attachments" text[],
	"is_verified_service" boolean DEFAULT true,
	"helpful_count" integer DEFAULT 0,
	"unhelpful_count" integer DEFAULT 0,
	"status" varchar(20) DEFAULT 'published',
	"moderation_notes" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "rating_score_check" CHECK (rating_score BETWEEN 1 AND 5),
	CONSTRAINT "rating_status_check" CHECK (status IN ('pending_review','published','hidden','flagged'))
);
--> statement-breakpoint
CREATE TABLE "service" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "service_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"description" text NOT NULL,
	"service_type_id" bigint NOT NULL,
	"provider_id" bigint NOT NULL,
	"custom_price" numeric(12,2),
	"availability_status" varchar(20) DEFAULT 'available',
	"response_time_hours" smallint DEFAULT 24,
	"years_of_experience" integer,
	"certifications" text,
	"equipment_owned" text[],
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "availability_status_check" CHECK (availability_status IN ('available', 'busy', 'unavailable'))
);
--> statement-breakpoint
CREATE TABLE "service_assignment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "service_assignment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"service_request_id" bigint NOT NULL,
	"provider_id" bigint NOT NULL,
	"quote_id" bigint,
	"assigned_date" timestamp with time zone DEFAULT now() NOT NULL,
	"scheduled_start" timestamp with time zone,
	"scheduled_end" timestamp with time zone,
	"actual_start" timestamp with time zone,
	"actual_end" timestamp with time zone,
	"status" varchar(30) DEFAULT 'assigned',
	"cancellation_reason" varchar(255),
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "assignment_status_check" CHECK (status IN ('assigned','in_progress','on_hold','completed','cancelled'))
);
--> statement-breakpoint
CREATE TABLE "service_category" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "service_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"description" text,
	"code" varchar NOT NULL UNIQUE,
	"icon_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "service_request" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "service_request_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"service_type_id" bigint NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"location_latitude" numeric(10,8) NOT NULL,
	"location_longitude" numeric(11,8) NOT NULL,
	"location_address" varchar(500),
	"preferred_date" date,
	"preferred_time_start" time,
	"preferred_time_end" time,
	"urgency_level" varchar(20) DEFAULT 'normal',
	"estimated_budget" numeric(12,2),
	"attachments" text[],
	"status" varchar(30) DEFAULT 'pending',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"completed_at" timestamp,
	"cancelled_at" timestamp,
	"cancellation_reason" varchar(255),
	"created_country_code" varchar(5) DEFAULT 'TG',
	CONSTRAINT "urgency_level_check" CHECK (urgency_level IN ('low', 'normal', 'high', 'emergency')),
	CONSTRAINT "status_check" CHECK (status IN ('pending', 'quoted', 'accepted', 'in_progress', 'completed', 'cancelled', 'disputed'))
);
--> statement-breakpoint
CREATE TABLE "service_type" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "service_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"description" text NOT NULL,
	"base_price" numeric(12,2),
	"price_unit" varchar(20),
	"estimated_duration_minutes" integer,
	"estimated_arrival_minutes" integer,
	"requires_site_visit" boolean DEFAULT true,
	"category_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "price_unit_check" CHECK (price_unit IN ('per_hour', 'per_day', 'per_project', 'fixed'))
);
--> statement-breakpoint
CREATE TABLE "transaction" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "transaction_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"service_request_id" bigint NOT NULL,
	"service_assignment_id" bigint,
	"user_id" bigint NOT NULL,
	"provider_id" bigint NOT NULL,
	"payment_method_id" bigint,
	"transaction_type" varchar(20) NOT NULL,
	"amount" numeric(12,2) NOT NULL,
	"currency" varchar(3) DEFAULT 'XOF',
	"transaction_status" varchar(30) DEFAULT 'pending',
	"mobile_money_reference" varchar(100),
	"mobile_money_provider" varchar(50),
	"mobile_money_destination" varchar(20),
	"cash_collected_by" varchar(100),
	"cash_collection_location" varchar(255),
	"description" text,
	"failure_reason" varchar(255),
	"notes" text,
	"ip_address" varchar(45),
	"device_info" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "transaction_type_check" CHECK (transaction_type IN ('deposit','service_payment','provider_payout','refund','platform_fee')),
	CONSTRAINT "transaction_status_check" CHECK (transaction_status IN ('pending','processing','completed','failed','refunded','cancelled'))
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"phone_number" varchar(20) NOT NULL UNIQUE,
	"password" text NOT NULL,
	"firebase_token" text NOT NULL,
	"refresh_token" text,
	"email" varchar(255) UNIQUE,
	"first_name" varchar(100) NOT NULL,
	"last_name" varchar(100) NOT NULL,
	"profile_photo_url" text,
	"user_type" varchar(20) NOT NULL,
	"country_code" varchar(5) DEFAULT 'TG',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"last_login_at" timestamp,
	"is_active" boolean DEFAULT true,
	"is_verified" boolean DEFAULT false,
	"verification_token" varchar(255),
	"verification_token_expires_at" timestamp,
	CONSTRAINT "user_type_check" CHECK (user_type IN ('customer', 'admin', 'support'))
);
--> statement-breakpoint
CREATE TABLE "user_preference" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_preference_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL UNIQUE,
	"language" varchar(10) DEFAULT 'fr',
	"notification_enabled" boolean DEFAULT true,
	"sms_notifications" boolean DEFAULT true,
	"push_notifications" boolean DEFAULT true,
	"preferred_service_categories" text[],
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "idx_mobile_money_transaction_transaction" ON "mobile_money_transaction" ("transaction_id");--> statement-breakpoint
CREATE INDEX "idx_mobile_money_transaction_reference" ON "mobile_money_transaction" ("external_reference_id");--> statement-breakpoint
CREATE INDEX "idx_notification_user" ON "notification" ("user_id");--> statement-breakpoint
CREATE INDEX "idx_notification_read" ON "notification" ("is_read");--> statement-breakpoint
CREATE INDEX "idx_notification_created" ON "notification" ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_payment_method_user" ON "payment_method" ("user_id");--> statement-breakpoint
CREATE INDEX "idx_payment_method_type" ON "payment_method" ("payment_type");--> statement-breakpoint
CREATE INDEX "idx_provider_active" ON "provider" ("is_active");--> statement-breakpoint
CREATE INDEX "idx_provider_verified" ON "provider" ("is_verified");--> statement-breakpoint
CREATE INDEX "idx_provider_company" ON "provider" ("company_name");--> statement-breakpoint
CREATE UNIQUE INDEX "provider_availability_unique" ON "provider_availability" ("provider_id","day_of_week");--> statement-breakpoint
CREATE INDEX "idx_provider_availability_provider" ON "provider_availability" ("provider_id");--> statement-breakpoint
CREATE INDEX "idx_provider_metrics_trustworthiness" ON "provider_metric" ("trustworthiness_score" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_rating_provider" ON "rating" ("provider_id");--> statement-breakpoint
CREATE INDEX "idx_rating_score" ON "rating" ("rating_score" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_rating_status" ON "rating" ("status");--> statement-breakpoint
CREATE INDEX "idx_rating_request" ON "rating" ("service_request_id");--> statement-breakpoint
CREATE INDEX "idx_rating_provider_published" ON "rating" ("provider_id","rating_score") WHERE "status" = 'published';--> statement-breakpoint
CREATE UNIQUE INDEX "provider_service_unique" ON "service" ("provider_id","service_type_id");--> statement-breakpoint
CREATE INDEX "idx_service_provider" ON "service" ("provider_id");--> statement-breakpoint
CREATE INDEX "idx_service_service_type" ON "service" ("service_type_id");--> statement-breakpoint
CREATE INDEX "idx_service_availability" ON "service" ("service_type_id","availability_status");--> statement-breakpoint
CREATE INDEX "idx_service_assignment_request" ON "service_assignment" ("service_request_id");--> statement-breakpoint
CREATE INDEX "idx_service_assignment_provider" ON "service_assignment" ("provider_id");--> statement-breakpoint
CREATE INDEX "idx_service_assignment_status" ON "service_assignment" ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "service_assignment_request_unique" ON "service_assignment" ("service_request_id");--> statement-breakpoint
CREATE INDEX "idx_service_request_user" ON "service_request" ("user_id");--> statement-breakpoint
CREATE INDEX "idx_service_request_status" ON "service_request" ("status");--> statement-breakpoint
CREATE INDEX "idx_service_request_service" ON "service_request" ("service_type_id");--> statement-breakpoint
CREATE INDEX "idx_service_request_created" ON "service_request" ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_service_request_status_created" ON "service_request" ("status","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_service_type_category" ON "service_type" ("category_id");--> statement-breakpoint
CREATE INDEX "idx_transaction_user" ON "transaction" ("user_id");--> statement-breakpoint
CREATE INDEX "idx_transaction_provider" ON "transaction" ("provider_id");--> statement-breakpoint
CREATE INDEX "idx_transaction_status" ON "transaction" ("transaction_status");--> statement-breakpoint
CREATE INDEX "idx_transaction_type" ON "transaction" ("transaction_type");--> statement-breakpoint
CREATE INDEX "idx_transaction_created" ON "transaction" ("created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "idx_transaction_request" ON "transaction" ("service_request_id");--> statement-breakpoint
CREATE INDEX "idx_transaction_completion" ON "transaction" ("user_id","created_at" DESC NULLS LAST) WHERE "transaction_status" = 'completed';--> statement-breakpoint
CREATE INDEX "idx_user_phone" ON "user" ("phone_number");--> statement-breakpoint
CREATE INDEX "idx_user_email" ON "user" ("email");--> statement-breakpoint
CREATE INDEX "idx_user_type" ON "user" ("user_type");--> statement-breakpoint
CREATE INDEX "idx_user_active" ON "user" ("is_active");--> statement-breakpoint
ALTER TABLE "mobile_money_transaction" ADD CONSTRAINT "mobile_money_transaction_transaction_id_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id");--> statement-breakpoint
ALTER TABLE "notification" ADD CONSTRAINT "notification_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "payment_method" ADD CONSTRAINT "payment_method_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "provider_availability" ADD CONSTRAINT "provider_availability_provider_id_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider"("id");--> statement-breakpoint
ALTER TABLE "provider_metric" ADD CONSTRAINT "provider_metric_provider_id_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "rating" ADD CONSTRAINT "rating_service_request_id_service_request_id_fkey" FOREIGN KEY ("service_request_id") REFERENCES "service_request"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "rating" ADD CONSTRAINT "rating_provider_id_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "rating" ADD CONSTRAINT "rating_rater_id_user_id_fkey" FOREIGN KEY ("rater_id") REFERENCES "user"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "service" ADD CONSTRAINT "service_service_type_id_service_type_id_fkey" FOREIGN KEY ("service_type_id") REFERENCES "service_type"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "service" ADD CONSTRAINT "service_provider_id_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider"("id");--> statement-breakpoint
ALTER TABLE "service_assignment" ADD CONSTRAINT "service_assignment_service_request_id_service_request_id_fkey" FOREIGN KEY ("service_request_id") REFERENCES "service_request"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "service_assignment" ADD CONSTRAINT "service_assignment_provider_id_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "service_request" ADD CONSTRAINT "service_request_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "service_request" ADD CONSTRAINT "service_request_service_type_id_service_type_id_fkey" FOREIGN KEY ("service_type_id") REFERENCES "service_type"("id");--> statement-breakpoint
ALTER TABLE "service_type" ADD CONSTRAINT "service_type_category_id_service_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "service_category"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "transaction" ADD CONSTRAINT "transaction_service_request_id_service_request_id_fkey" FOREIGN KEY ("service_request_id") REFERENCES "service_request"("id");--> statement-breakpoint
ALTER TABLE "transaction" ADD CONSTRAINT "transaction_service_assignment_id_service_assignment_id_fkey" FOREIGN KEY ("service_assignment_id") REFERENCES "service_assignment"("id");--> statement-breakpoint
ALTER TABLE "transaction" ADD CONSTRAINT "transaction_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id");--> statement-breakpoint
ALTER TABLE "transaction" ADD CONSTRAINT "transaction_provider_id_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "provider"("id");--> statement-breakpoint
ALTER TABLE "transaction" ADD CONSTRAINT "transaction_payment_method_id_payment_method_id_fkey" FOREIGN KEY ("payment_method_id") REFERENCES "payment_method"("id");--> statement-breakpoint
ALTER TABLE "user_preference" ADD CONSTRAINT "user_preference_user_id_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;